version: '3.8'

services:

    api: # Main API gateway
        image: docker.saturnserver.org/birthday-bot/api:latest
        environment:
            - DEBUG
            - BB_API_PORT
            - BB_STORAGE_URL
            - BB_STORAGE_PORT
            - BB_DISCORD_CLIENT_PORT
            - BB_DISCORD_CLIENT_URL
        restart: unless-stopped

    calendar: # Birthday notification trigger
        image: docker.saturnserver.org/birthday-bot/calendar:latest
        environment:
            - DEBUG
            - BB_API_PORT
            - BB_API_URL
        restart: unless-stopped

    discord-client: # Discord client
        image: docker.saturnserver.org/birthday-bot/discord-client:latest
        environment:
            - DEBUG
            - BB_API_PORT
            - BB_API_URL
            - BB_DISCORD_CLIENT_PORT
            - BB_DISCORD_GUILDS
            - BB_DISCORD_TOKEN
            - BB_DISCORD_ID
            - BB_DISCORD_KEY
        restart: unless-stopped

    storage: # Birthday service
        image: docker.saturnserver.org/birthday-bot/storage:latest
        environment:
            - DEBUG
            - BB_API_PORT
            - BB_API_URL
            - BB_STORAGE_PORT
            - BB_STORAGE_DB_NAME
        restart: unless-stopped
        volumes:
            - ${BB_DB_VOLUME}:/app/data
